# Generated by Django 3.1 on 2020-09-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user',
            new_name='emitter',
        ),
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.CharField(default='text by default', max_length=200),
            preserve_default=False,
        ),
    ]
